version: '3.7'

services:
  medic-os-three:
    container_name: medic-os-three
    image: medicmobile/medic-os:cht-3.9.0-rc.2
    volumes:
      - medic-data-three:/srv
    ports:
      - 8080:80
      - 444:443
    working_dir: /srv
    depends_on:
      - haproxy-three
    networks:
      - medic-net-three
    environment:
      - DOCKER_NETWORK_NAME=haproxy-three
      - DOCKER_COUCHDB_ADMIN_PASSWORD=$DOCKER_COUCHDB_ADMIN_PASSWORD

  haproxy-three:
    container_name: haproxy-three
    image: medicmobile/haproxy:rc-1.17
    volumes:
      - medic-data-three:/srv    
    environment:
      - COUCHDB_HOST=medic-os-three
      - HA_PASSWORD=$DOCKER_COUCHDB_ADMIN_PASSWORD
    networks:
      - medic-net-three

volumes:
  medic-data-three:
    name: medic-data-three

networks:
  medic-net-three:
    name: medic-net-three